version: '2.1'
orbs:
  snyk: snyk/snyk@2.1.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: high
workflows: null
