version: '2.1'
orbs:
  snyk: snyk/snyk@2.1.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
        Fail-on-issues: false
        monitor-on-build: true
        token-variable: SNYK_TOKEN
workflows: null
