version: '2.1'
orbs:
  snyk: snyk/snyk@2.1.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run:
          command: snyk code test
      - snyk/scan:
          fail-on-issues: false
workflows: null
